name: ci

on:
  push:
    tags: ["v*"]
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

    - run: uv tool install ruff

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y libgtk-3-dev
        uv sync

    - name: check code
      shell: bash
      run: ruff check .

  compile:

    if: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') }}
    needs: ["build"]
    strategy:
      max-parallel: 4
      matrix:
        os: ["ubuntu", "windows"]

    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v7

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

    - name: Install dependencies
      shell: bash
      env:
        OS: ${{ matrix.os }}
      run: |
        if [[ "${OS,,}" == "ubuntu" ]]; then
        sudo apt update -y
        sudo apt install -y libgtk-3-dev
        fi
        uv sync

    - name: building executable
      shell: bash
      env:
        OS: ${{ matrix.os }}
      run: uv build && uv run pyinstaller --noconsole -F tg-file-exporter.pyw -n tg-file-exporter-$OS


    - uses: actions/upload-artifact@v7
      with:
        name: exe_for_${{ matrix.os }}_${{ matrix.architecture }}
        path: dist/tg-file-exporter*

  uploadrelease:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') }}
    needs: ["build", "compile"]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v7
    - name: download releases files
      uses: actions/download-artifact@v8
      with:
        path: /tmp/
    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        files: /tmp/exe_for_*/tg-file-exporter*
        fail_on_unmatched_files: true
        # append_body: true

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

    - name: Install dependencies
      run: |
        sudo apt update -y || true
        sudo apt install -y libgtk-3-dev || true
        uv sync

    - name: build
      run: |
        uv build

    - name: Publish to pypi
      run: |
        uv publish
      env:
        UV_PUBLISH_USERNAME: __token__
        UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_TOKEN }}
